export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('region').del()

  // Inserts seed entries
  await knex('region').insert([
    { id: 1, name: 'Far North', hardiness_zone: '9a', notes: '' },
    { id: 2, name: 'Whangarei', hardiness_zone: '9b', notes: '' },
    { id: 3, name: 'Kaipara', hardiness_zone: '9b', notes: '' },
    { id: 4, name: 'Auckland', hardiness_zone: '10a', notes: '' },
    { id: 5, name: 'Thames-Coromandel', hardiness_zone: '10a', notes: '' },
    { id: 6, name: 'Hauraki', hardiness_zone: '10a', notes: '' },
    { id: 7, name: 'Waikato', hardiness_zone: '9b', notes: '' },
    { id: 8, name: 'Matamata-Piako', hardiness_zone: '9b', notes: '' },
    { id: 9, name: 'Hamilton', hardiness_zone: '9b', notes: '' },
    { id: 10, name: 'Waipa', hardiness_zone: '9b', notes: '' },
    { id: 11, name: 'Western Bay of Plenty', hardiness_zone: '10a', notes: '' },
    { id: 12, name: 'Tauranga', hardiness_zone: '10a', notes: '' },
    { id: 13, name: 'Kawerau', hardiness_zone: '10a', notes: '' },
    { id: 14, name: 'Whakatane', hardiness_zone: '10a', notes: '' },
    { id: 15, name: 'Rotorua', hardiness_zone: '9b', notes: '' },
    { id: 16, name: 'Opotiki', hardiness_zone: '10a', notes: '' },
    { id: 17, name: 'Gisborne', hardiness_zone: '10a', notes: '' },
    { id: 18, name: 'Wairoa', hardiness_zone: '9b', notes: '' },
    { id: 19, name: 'Taupo', hardiness_zone: '9a', notes: '' },
    { id: 20, name: 'South Waikato', hardiness_zone: '9b', notes: '' },
    { id: 21, name: 'Otorohanga', hardiness_zone: '9b', notes: '' },
    { id: 22, name: 'Waitomo', hardiness_zone: '9b', notes: '' },
    { id: 23, name: 'Napier', hardiness_zone: '10a', notes: '' },
    { id: 24, name: 'Hastings', hardiness_zone: '10a', notes: '' },
    { id: 25, name: 'Ruapehu', hardiness_zone: '8b', notes: '' },
    { id: 26, name: 'New Plymouth', hardiness_zone: '10a', notes: '' },
    { id: 27, name: 'South Taranaki', hardiness_zone: '9b', notes: '' },
    { id: 28, name: 'Stratford', hardiness_zone: '9b', notes: '' },
    { id: 29, name: 'Central Hawkes Bay', hardiness_zone: '10a', notes: '' },
    { id: 30, name: 'Whanganui', hardiness_zone: '9b', notes: '' },
    { id: 31, name: 'Rangitikei', hardiness_zone: '9b', notes: '' },
    { id: 32, name: 'Manawatu', hardiness_zone: '9b', notes: '' },
    { id: 33, name: 'Horowhenua', hardiness_zone: '9b', notes: '' },
    { id: 34, name: 'Tararuas', hardiness_zone: '9a', notes: '' },
    { id: 35, name: 'Palmerston North', hardiness_zone: '9b', notes: '' },
    { id: 36, name: 'Masterton', hardiness_zone: '9b', notes: '' },
    { id: 37, name: 'Carteron', hardiness_zone: '9b', notes: '' },
    { id: 38, name: 'South Wairarapa', hardiness_zone: '9b', notes: '' },
    { id: 39, name: 'Wellington', hardiness_zone: '9b', notes: '' },
    { id: 40, name: 'Lower Hutt', hardiness_zone: '9b', notes: '' },
    { id: 41, name: 'Upper Hutt', hardiness_zone: '9b', notes: '' },
    { id: 42, name: 'Kapiti Coast', hardiness_zone: '10a', notes: '' },
    { id: 43, name: 'Porirua', hardiness_zone: '9b', notes: '' },
    { id: 44, name: 'Nelson', hardiness_zone: '10a', notes: '' },
    { id: 45, name: 'Marlborough', hardiness_zone: '10a', notes: '' },
    { id: 46, name: 'Tasman', hardiness_zone: '10a', notes: '' },
    { id: 47, name: 'Buller', hardiness_zone: '9a', notes: '' },
    { id: 48, name: 'Kaikoura', hardiness_zone: '9b', notes: '' },
    { id: 49, name: 'Hurunui', hardiness_zone: '9b', notes: '' },
    { id: 50, name: 'Waimakariri', hardiness_zone: '9a', notes: '' },
    { id: 51, name: 'Grey', hardiness_zone: '9a', notes: '' },
    { id: 52, name: 'Christchurch', hardiness_zone: '9a', notes: '' },
    { id: 53, name: 'Selwyn', hardiness_zone: '9a', notes: '' },
    { id: 54, name: 'Ashburton', hardiness_zone: '9a', notes: '' },
    { id: 55, name: 'Timaru', hardiness_zone: '9a', notes: '' },
    { id: 56, name: 'Westland', hardiness_zone: '9a', notes: '' },
    { id: 57, name: 'Mackenzie', hardiness_zone: '8b', notes: '' },
    { id: 58, name: 'Waimate', hardiness_zone: '9a', notes: '' },
    { id: 59, name: 'Waitaki', hardiness_zone: '9a', notes: '' },
    { id: 60, name: 'Central Otago', hardiness_zone: '8b', notes: '' },
    { id: 61, name: 'Dunedin', hardiness_zone: '9a', notes: '' },
    { id: 62, name: 'Clutha', hardiness_zone: '9a', notes: '' },
    { id: 63, name: 'Foveaux', hardiness_zone: '9a', notes: '' },
    { id: 64, name: 'Invercargill', hardiness_zone: '8b', notes: '' },
    { id: 65, name: 'Southland', hardiness_zone: '8b', notes: '' },
    { id: 66, name: 'Queenstown Lakes', hardiness_zone: '8b', notes: '' },
  ])
}
