export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('season').del()

  await knex('season').insert([
    {
      id: 1,
      vege_id: 1,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 2,
      vege_id: 1,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 3,
      vege_id: 1,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 4,
      vege_id: 1,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 5,
      vege_id: 2,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 6,
      vege_id: 2,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 7,
      vege_id: 2,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct,Nov',
    },
    {
      id: 8,
      vege_id: 2,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 9,
      vege_id: 3,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 10,
      vege_id: 3,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 11,
      vege_id: 3,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 12,
      vege_id: 3,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 13,
      vege_id: 4,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 14,
      vege_id: 4,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 15,
      vege_id: 4,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 16,
      vege_id: 4,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 17,
      vege_id: 5,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 18,
      vege_id: 5,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 19,
      vege_id: 5,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 20,
      vege_id: 5,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 21,
      vege_id: 6,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 22,
      vege_id: 6,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 23,
      vege_id: 6,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 24,
      vege_id: 6,
      hardiness_zone: '8b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 25,
      vege_id: 7,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 26,
      vege_id: 7,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 27,
      vege_id: 7,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 28,
      vege_id: 7,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 29,
      vege_id: 8,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 30,
      vege_id: 8,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 31,
      vege_id: 8,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 32,
      vege_id: 8,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 33,
      vege_id: 9,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 34,
      vege_id: 9,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 35,
      vege_id: 9,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 36,
      vege_id: 9,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 37,
      vege_id: 10,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 38,
      vege_id: 10,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 39,
      vege_id: 10,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 40,
      vege_id: 10,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 41,
      vege_id: 11,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 42,
      vege_id: 11,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 43,
      vege_id: 11,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 44,
      vege_id: 11,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 45,
      vege_id: 12,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 46,
      vege_id: 12,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 47,
      vege_id: 12,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 48,
      vege_id: 12,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 49,
      vege_id: 13,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 50,
      vege_id: 13,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 51,
      vege_id: 13,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 52,
      vege_id: 13,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 53,
      vege_id: 14,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 54,
      vege_id: 14,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 55,
      vege_id: 14,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 56,
      vege_id: 14,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 57,
      vege_id: 15,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 58,
      vege_id: 15,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 59,
      vege_id: 15,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 60,
      vege_id: 15,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 61,
      vege_id: 16,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 62,
      vege_id: 16,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 63,
      vege_id: 16,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 64,
      vege_id: 16,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 65,
      vege_id: 17,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 66,
      vege_id: 17,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 67,
      vege_id: 17,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 68,
      vege_id: 17,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 69,
      vege_id: 18,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 70,
      vege_id: 18,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 71,
      vege_id: 18,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 72,
      vege_id: 18,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 73,
      vege_id: 19,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 74,
      vege_id: 19,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 75,
      vege_id: 19,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 76,
      vege_id: 19,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 77,
      vege_id: 20,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 78,
      vege_id: 20,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 79,
      vege_id: 20,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 80,
      vege_id: 20,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 81,
      vege_id: 21,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 82,
      vege_id: 21,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 83,
      vege_id: 21,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 84,
      vege_id: 21,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 85,
      vege_id: 22,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 86,
      vege_id: 22,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 87,
      vege_id: 22,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 88,
      vege_id: 22,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 89,
      vege_id: 23,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 90,
      vege_id: 23,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 91,
      vege_id: 23,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 92,
      vege_id: 23,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 93,
      vege_id: 24,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 94,
      vege_id: 24,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 95,
      vege_id: 24,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 96,
      vege_id: 24,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 97,
      vege_id: 25,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 98,
      vege_id: 25,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 99,
      vege_id: 25,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 100,
      vege_id: 25,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 101,
      vege_id: 26,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 102,
      vege_id: 26,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 103,
      vege_id: 26,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 104,
      vege_id: 26,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 105,
      vege_id: 27,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 106,
      vege_id: 27,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 107,
      vege_id: 27,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 108,
      vege_id: 27,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 109,
      vege_id: 28,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 110,
      vege_id: 28,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 111,
      vege_id: 28,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 112,
      vege_id: 28,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 113,
      vege_id: 29,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 114,
      vege_id: 29,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 115,
      vege_id: 29,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 116,
      vege_id: 29,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 117,
      vege_id: 30,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 118,
      vege_id: 30,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 119,
      vege_id: 30,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 120,
      vege_id: 30,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 121,
      vege_id: 31,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 122,
      vege_id: 31,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 123,
      vege_id: 31,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 124,
      vege_id: 31,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 125,
      vege_id: 32,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 126,
      vege_id: 32,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 127,
      vege_id: 32,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 128,
      vege_id: 32,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 129,
      vege_id: 33,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 130,
      vege_id: 33,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 131,
      vege_id: 33,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 132,
      vege_id: 33,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Nov,Dec,Jan',
    },
    {
      id: 133,
      vege_id: 34,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 134,
      vege_id: 34,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 135,
      vege_id: 34,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 136,
      vege_id: 34,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 137,
      vege_id: 35,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 138,
      vege_id: 35,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 139,
      vege_id: 35,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 140,
      vege_id: 35,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 141,
      vege_id: 36,
      hardiness_zone: '9a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 142,
      vege_id: 36,
      hardiness_zone: '9b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 143,
      vege_id: 36,
      hardiness_zone: '10a',
      planting_month: 'Aug,Sep,Oct',
      harvest_month: 'Dec,Jan,Feb',
    },
    {
      id: 144,
      vege_id: 36,
      hardiness_zone: '8b',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar',
    },
  ])
}
