export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('season').del()

  await knex('season').insert([
    {
      id: 1,
      vege_id: 1,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 2,
      vege_id: 1,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 3,
      vege_id: 1,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 4,
      vege_id: 1,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 5,
      vege_id: 2,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 6,
      vege_id: 2,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov,Dec',
    },
    {
      id: 7,
      vege_id: 2,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Aug,Sep,Oct,Nov',
    },
    {
      id: 8,
      vege_id: 2,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 9,
      vege_id: 3,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 10,
      vege_id: 3,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 11,
      vege_id: 3,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 12,
      vege_id: 3,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Mar,Apr,May,Jun',
    },
    {
      id: 13,
      vege_id: 4,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 14,
      vege_id: 4,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 15,
      vege_id: 4,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 16,
      vege_id: 4,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 17,
      vege_id: 5,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 18,
      vege_id: 5,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 19,
      vege_id: 5,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 20,
      vege_id: 5,
      hardiness_zone: '8b',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 21,
      vege_id: 6,
      hardiness_zone: '9a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 22,
      vege_id: 6,
      hardiness_zone: '9b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 23,
      vege_id: 6,
      hardiness_zone: '10a',
      planting_month: 'Feb,Mar,Apr',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 24,
      vege_id: 6,
      hardiness_zone: '8b',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 25,
      vege_id: 7,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 26,
      vege_id: 7,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 27,
      vege_id: 7,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 28,
      vege_id: 7,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 29,
      vege_id: 8,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 30,
      vege_id: 8,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 31,
      vege_id: 8,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 32,
      vege_id: 8,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Oct,Nov,Dec',
    },
    {
      id: 33,
      vege_id: 9,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 34,
      vege_id: 9,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 35,
      vege_id: 9,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 36,
      vege_id: 9,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 37,
      vege_id: 10,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 38,
      vege_id: 10,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 39,
      vege_id: 10,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 40,
      vege_id: 10,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 41,
      vege_id: 11,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 42,
      vege_id: 11,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 43,
      vege_id: 11,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Aug,Sep,Oct',
    },
    {
      id: 44,
      vege_id: 11,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Sep,Oct,Nov',
    },
    {
      id: 45,
      vege_id: 12,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 46,
      vege_id: 12,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 47,
      vege_id: 12,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar',
    },
    {
      id: 48,
      vege_id: 12,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr',
    },
    {
      id: 49,
      vege_id: 13,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 50,
      vege_id: 13,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 51,
      vege_id: 13,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 52,
      vege_id: 13,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 53,
      vege_id: 14,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 54,
      vege_id: 14,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 55,
      vege_id: 14,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 56,
      vege_id: 14,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 57,
      vege_id: 15,
      hardiness_zone: '9a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 58,
      vege_id: 15,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 59,
      vege_id: 15,
      hardiness_zone: '10a',
      planting_month: 'Sep,Oct,Nov',
      harvest_month: 'Oct,Nov,Dec,Jan',
    },
    {
      id: 60,
      vege_id: 15,
      hardiness_zone: '8b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Nov,Dec,Jan,Feb',
    },
    {
      id: 61,
      vege_id: 16,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 62,
      vege_id: 16,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 63,
      vege_id: 16,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Mar,Apr,May',
    },
    {
      id: 64,
      vege_id: 16,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Apr,May,Jun',
    },
    {
      id: 65,
      vege_id: 17,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 66,
      vege_id: 17,
      hardiness_zone: '9b',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 67,
      vege_id: 17,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 68,
      vege_id: 17,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 69,
      vege_id: 18,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 70,
      vege_id: 18,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 71,
      vege_id: 18,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 72,
      vege_id: 18,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Feb,Mar,Apr,May',
    },
    {
      id: 73,
      vege_id: 19,
      hardiness_zone: '9a',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 74,
      vege_id: 19,
      hardiness_zone: '9b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 75,
      vege_id: 19,
      hardiness_zone: '10a',
      planting_month: 'Oct,Nov,Dec',
      harvest_month: 'Dec,Jan,Feb,Mar',
    },
    {
      id: 76,
      vege_id: 19,
      hardiness_zone: '8b',
      planting_month: 'Nov,Dec,Jan',
      harvest_month: 'Jan,Feb,Mar,Apr',
    },
    {
      id: 77,
      vege_id: 20,
      hardiness_zone: '9a',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 78,
      vege_id: 20,
      hardiness_zone: '9b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
    {
      id: 79,
      vege_id: 20,
      hardiness_zone: '10a',
      planting_month: 'Mar,Apr,May',
      harvest_month: 'Jun,Jul,Aug,Sep',
    },
    {
      id: 80,
      vege_id: 20,
      hardiness_zone: '8b',
      planting_month: 'Apr,May,Jun',
      harvest_month: 'Jul,Aug,Sep,Oct',
    },
  ])
}
