export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('variety').del()

  // Inserts seed entries
  await knex('variety').insert([
    {
      id: 1,
      vege_id: '1',
      name: 'Kennebec',
      notes: 'Common cultivar: Kennebec',
    },
    {
      id: 2,
      vege_id: '1',
      name: 'Agria',
      notes: 'Common cultivar: Agria',
    },
    {
      id: 3,
      vege_id: '1',
      name: 'Desiree',
      notes: 'Common cultivar: Desiree',
    },
    {
      id: 4,
      vege_id: '2',
      name: 'Red Burgundy',
      notes: 'Common cultivar: Red Burgundy',
    },
    {
      id: 5,
      vege_id: '2',
      name: 'White Lisbon',
      notes: 'Common cultivar: White Lisbon',
    },
    {
      id: 6,
      vege_id: '2',
      name: 'Brown Spanish',
      notes: 'Common cultivar: Brown Spanish',
    },
    {
      id: 7,
      vege_id: '3',
      name: 'Butternut',
      notes: 'Common cultivar: Butternut',
    },
    {
      id: 8,
      vege_id: '3',
      name: 'Queensland Blue',
      notes: 'Common cultivar: Queensland Blue',
    },
    {
      id: 9,
      vege_id: '3',
      name: 'Hokkaido',
      notes: 'Common cultivar: Hokkaido',
    },
    {
      id: 10,
      vege_id: '4',
      name: 'Calabrese',
      notes: 'Common cultivar: Calabrese',
    },
    {
      id: 11,
      vege_id: '4',
      name: 'Belstar',
      notes: 'Common cultivar: Belstar',
    },
    {
      id: 12,
      vege_id: '4',
      name: 'Purple Sprouting',
      notes: 'Common cultivar: Purple Sprouting',
    },
    {
      id: 13,
      vege_id: '5',
      name: 'Snowball Y',
      notes: 'Common cultivar: Snowball Y',
    },
    {
      id: 14,
      vege_id: '5',
      name: 'Graffiti',
      notes: 'Common cultivar: Graffiti',
    },
    {
      id: 15,
      vege_id: '5',
      name: 'Cheddar',
      notes: 'Common cultivar: Cheddar',
    },
    {
      id: 16,
      vege_id: '6',
      name: 'Golden Acre',
      notes: 'Common cultivar: Golden Acre',
    },
    {
      id: 17,
      vege_id: '6',
      name: 'Red Drumhead',
      notes: 'Common cultivar: Red Drumhead',
    },

    {
      id: 18,
      vege_id: '6',
      name: 'Brunswick',
      notes: 'Common cultivar: Brunswick',
    },
    {
      id: 19,
      vege_id: '7',
      name: 'Buttercrunch',
      notes: 'Common cultivar: Buttercrunch',
    },
    {
      id: 20,
      vege_id: '7',
      name: 'Cos/Romaine',
      notes: 'Common cultivar: Cos/Romaine',
    },
    {
      id: 21,
      vege_id: '7',
      name: 'Oakleaf',
      notes: 'Common cultivar: Oakleaf',
    },
    {
      id: 22,
      vege_id: '8',
      name: 'Bloomsdale',
      notes: 'Common cultivar: Bloomsdale',
    },

    {
      id: 24,
      vege_id: '8',
      name: 'Tyee',
      notes: 'Common cultivar: Tyee',
    },
    {
      id: 24,
      vege_id: '8',
      name: 'Giant Winter',
      notes: 'Common cultivar: Giant Winter',
    },
    {
      id: 25,
      vege_id: '9',
      name: 'Bright Lights',
      notes: 'Common cultivar: Bright Lights',
    },
    {
      id: 26,
      vege_id: '9',
      name: 'Fordhook Giant',
      notes: 'Common cultivar: Fordhook Giant',
    },
    {
      id: 27,
      vege_id: '9',
      name: 'Perpetual Spinach',
      notes: 'Common cultivar: Perpetual Spinach',
    },
    {
      id: 28,
      vege_id: '10',
      name: 'Winterbor',
      notes: 'Common cultivar: Winterbor',
    },
    {
      id: 29,
      vege_id: '10',
      name: 'Red Russian',
      notes: 'Common cultivar: Red Russian',
    },
    {
      id: 30,
      vege_id: '10',
      name: 'Curly Kale',
      notes: 'Common cultivar: Curly Kale',
    },
    {
      id: 31,
      vege_id: '11',
      name: 'Sugar Snap',
      notes: 'Common cultivar: Sugar Snap',
    },
    {
      id: 32,
      vege_id: '11',
      name: 'Oregon Giant',
      notes: 'Common cultivar: Oregon Giant',
    },
    {
      id: 33,
      vege_id: '11',
      name: 'Green Arrow',
      notes: 'Common cultivar: Green Arrow',
    },
    {
      id: 34,
      vege_id: '12',
      name: 'Blue Lake',
      notes: 'Common cultivar: Blue Lake',
    },
    {
      id: 35,
      vege_id: '12',
      name: 'Scarlet Runner',
      notes: 'Common cultivar: Scarlet Runner',
    },
    {
      id: 36,
      vege_id: '12',
      name: 'Broad Windsor',
      notes: 'Common cultivar: Broad Windsor',
    },
    {
      id: 37,
      vege_id: '13',
      name: 'Nantes',
      notes: 'Common cultivar: Nantes',
    },
    {
      id: 38,
      vege_id: '13',
      name: 'Chantenay',
      notes: 'Common cultivar: Chantenay',
    },
    {
      id: 39,
      vege_id: '13',
      name: 'Imperator',
      notes: 'Common cultivar: Imperator',
    },
    {
      id: 40,
      vege_id: '14',
      name: 'Detroit Dark Red',
      notes: 'Common cultivar: Detroit Dark Red',
    },
    {
      id: 41,
      vege_id: '14',
      name: 'Boltardy',
      notes: 'Common cultivar: Boltardy',
    },
    {
      id: 42,
      vege_id: '14',
      name: 'Chioggia',
      notes: 'Common cultivar: Chioggia',
    },
    {
      id: 43,
      vege_id: '15',
      name: 'Javelin',
      notes: 'Common cultivar: Javelin',
    },
    {
      id: 44,
      vege_id: '15',
      name: 'Gladiator',
      notes: 'Common cultivar: Gladiator',
    },
    {
      id: 45,
      vege_id: '15',
      name: 'Tender and True',
      notes: 'Common cultivar: Tender and True',
    },
    {
      id: 46,
      vege_id: '16',
      name: 'Beauregard',
      notes: 'Common cultivar: Beauregard',
    },
    {
      id: 47,
      vege_id: '16',
      name: 'Owairaka Red',
      notes: 'Common cultivar: Owairaka Red',
    },
    {
      id: 48,
      vege_id: '16',
      name: 'Toka',
      notes: 'Common cultivar: Toka',
    },
    {
      id: 49,
      vege_id: '17',
      name: 'Roma',
      notes: 'Common cultivar: Roma',
    },
    {
      id: 50,
      vege_id: '17',
      name: 'Sungold',
      notes: 'Common cultivar: Sungold',
    },
    {
      id: 51,
      vege_id: '17',
      name: 'Moneymaker',
      notes: 'Common cultivar: Moneymaker',
    },
    {
      id: 52,
      vege_id: '18',
      name: 'California Wonder',
      notes: 'Common cultivar: California Wonder',
    },
    {
      id: 53,
      vege_id: '18',
      name: 'Yolo Wonder',
      notes: 'Common cultivar: Yolo Wonder',
    },
    {
      id: 54,
      vege_id: '18',
      name: 'Corno di Toro',
      notes: 'Common cultivar: Corno di Toro',
    },
    {
      id: 55,
      vege_id: '19',
      name: 'Marketmore',
      notes: 'Common cultivar: Marketmore',
    },
    {
      id: 56,
      vege_id: '19',
      name: 'Spacemaster',
      notes: 'Common cultivar: Spacemaster',
    },
    {
      id: 57,
      vege_id: '19',
      name: 'Lemon Cucumber',
      notes: 'Common cultivar: Lemon Cucumber',
    },
    {
      id: 58,
      vege_id: '20',
      name: 'Hakurei',
      notes: 'Common cultivar: Hakurei',
    },
    {
      id: 59,
      vege_id: '20',
      name: 'Purple Top White Globe',
      notes: 'Common cultivar: Purple Top White Globe',
    },
    {
      id: 60,
      vege_id: '20',
      name: 'Tokyo Cross',
      notes: 'Common cultivar: Tokyo Cross',
    },
  ])
}
