export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('vegetables').del()

  // Inserts seed entries
  await knex('vegetables').insert([
    {
      id: 1,
      name: 'Potatoes',
      scientific_name: 'Solanum tuberosum',
      description: 'Tuberous crop grown underground; staple in many gardens.',
      soil_id: 1,
      spacing_id: 1,
      requirements_id: 1,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cool (10–15°C), dark, 2–4 months',
      image: '../../public/potato.webp',
      image2: '../../public/potatoes.webp',
      image3: '../../public/potatoes1.webp',
    },
    {
      id: 2,
      name: 'Onions',
      scientific_name: 'Allium cepa',
      description:
        'Bulb vegetable, grown from sets or seeds; good for long-term storage.',
      soil_id: 5,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage: 'Dry, ventilated, months',
      image: '../../public/onion.webp',
      image2: '../../public/onions.webp',
      image3: '../../public/onion1.webp',
    },
    {
      id: 3,
      name: 'Pumpkin / Squash',
      scientific_name: 'Cucurbita pepo',
      description:
        'Vining plant producing large, sweet fruit; great for storage.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 130,
      yield_per_plant_min: 2,
      yield_per_plant_max: 5,
      storage: 'Cure 7–10 days, store 2–4 months',
      image: '../../public/pumpkin.webp',
      image2: '../../public/pumpkinplant.webp',
      image3: '../../public/pumpkinplant1.webp',
    },
    {
      id: 4,
      name: 'Broccoli',
      scientific_name: 'Brassica oleracea var. italica',
      description: 'Edible flowering heads rich in nutrition.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Refrigerate 1–2°C, up to a week',
      image: '../../public/broccoli.webp',
      image2: '../../public/broccoli3.webp',
      image3: '../../public/broccoli2.webp',
    },
    {
      id: 5,
      name: 'Cauliflower',
      scientific_name: 'Brassica oleracea var. botrytis',
      description: 'Compact white heads; needs consistent growth.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.4,
      yield_per_plant_max: 1.0,
      storage: 'Refrigerate 1–2°C, use within a week',
      image: '../../public/cauliflower.webp',
      image2: '../../public/cauliflower1.webp',
      image3: '../../public/cauliflower2.webp',
    },
    {
      id: 6,
      name: 'Cabbage',
      scientific_name: 'Brassica oleracea var. capitata',
      description: 'Dense leafy head vegetable.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1.5,
      storage: 'Cool 0–2°C, several weeks',
      image: '../../public/cabbage.webp',
      image2: '../../public/cabbage3.webp',
      image3: '../../public/cabbage1.webp',
    },
    {
      id: 7,
      name: 'Lettuce',
      scientific_name: 'Lactuca sativa',
      description: 'Leafy salad green, prefers cool moist conditions.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Refrigerate 0–2°C, 5–7 days',
      image: '../../public/lettuce.webp',
      image2: '../../public/lettuce1.webp',
      image3: '../../public/lettuce2.webp',
    },
    {
      id: 8,
      name: 'Spinach',
      scientific_name: 'Spinacia oleracea',
      description: 'Leafy green, fast-growing in cool seasons.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 30,
      days_to_harvest_max: 50,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Refrigerate 0–2°C, use within days',
      image: '../../public/spinach.webp',
      image2: '../../public/spinach1.webp',
      image3: '../../public/spinach2.webp',
    },
    {
      id: 9,
      name: 'Silverbeet / Swiss Chard',
      scientific_name: 'Beta vulgaris subsp. cicla',
      description: 'Productive leafy green with colourful stems.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate 0–2°C, ~5–7 days',
      image: '../../public/silverbeet.webp',
      image2: '../../public/silverbeet1.webp',
      image3: '../../public/silverbeet3.webp',
    },
    {
      id: 10,
      name: 'Kale',
      scientific_name: 'Brassica oleracea var. sabellica',
      description: 'Hardy leafy green; tolerates frost.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate, use within 7–10 days',
      image: '../../public/kale.webp',
      image2: '../../public/kale1.webp',
      image3: '../../public/kale3.webp',
    },
    {
      id: 11,
      name: 'Peas (Garden / Snap)',
      scientific_name: 'Pisum sativum',
      description: 'Sweet pods, climbing or bush varieties.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 60,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate 0–2°C, 3–5 days',
      image: '../../public/sweet-pea.webp',
      image2: '../../public/peas1.webp',
      image3: '../../public/peas2.webp',
    },
    {
      id: 12,
      name: 'Beans (Green / Broad)',
      scientific_name: 'Phaseolus vulgaris',
      description: 'Climbing or bush legumes with edible pods.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate 0–2°C, 3–5 days',
      image: '../../public/green-beans.webp',
      image2: '../../public/greenbean1.webp',
      image3: '../../public/greenbean2.webp',
    },
    {
      id: 13,
      name: 'Carrots',
      scientific_name: 'Daucus carota',
      description: 'Root vegetable, prefers deep loose soil.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Cool, dark, ventilated, 2–3 months',
      image: '../../public/carrots.webp',
      image2: '../../public/carrots3.webp',
      image3: '../../public/carrots4.webp',
    },
    {
      id: 14,
      name: 'Beetroot',
      scientific_name: 'Beta vulgaris',
      description: 'Root vegetable; leaves edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.4,
      storage: 'Cool dark, 2–3 months',
      image: '../../public/beetroot.webp',
      image2: '../../public/beetroot1.webp',
      image3: '../../public/beetroot3.webp',
    },
    {
      id: 15,
      name: 'Parsnips',
      scientific_name: 'Pastinaca sativa',
      description: 'Sweet root crop; flavor improves after frost.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.5,
      storage: 'Cool, dark, ventilated; 3–4 months',
      image: '../../public/parsnip-plant.webp',
      image2: '../../public/parsnip1.webp',
      image3: '../../public/parsnip2.webp',
    },
    {
      id: 16,
      name: 'Kumara',
      scientific_name: 'Ipomoea batatas',
      description: 'Sweet potato; needs warm soil and curing before storage.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 100,
      days_to_harvest_max: 140,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cure 7–10 days, store at 12–15°C',
      image: '../../public/kumera.webp',
      image2: '../../public/kumera1.webp',
      image3: '../../public/kumera2.webp',
    },
    {
      id: 17,
      name: 'Tomatoes',
      scientific_name: 'Solanum lycopersicum',
      description: 'Warm-season fruiting plant; needs support.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 3,
      yield_per_plant_max: 6,
      storage: 'Best fresh; short refrigeration possible',
      image: '../../public/tomato.webp',
      image2: '../../public/tomatoes1.webp',
      image3: '../../public/tomatoplant2.webp',
    },
    {
      id: 18,
      name: 'Capsicum / Bell Peppers',
      scientific_name: 'Capsicum annuum',
      description: 'Warm-season fruiting vegetable, sweet or hot varieties.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 2,
      yield_per_plant_max: 4,
      storage: 'Cool, ~7–10°C, 1–2 weeks',
      image: '../../public/bell-pepper.webp',
      image2: '../../public/bellpepper.webp',
      image3: '../../public/bellpepper1.webp',
    },
    {
      id: 19,
      name: 'Cucumbers',
      scientific_name: 'Cucumis sativus',
      description: 'Vining summer crop, best supported on trellis.',
      soil_id: 1,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 3,
      yield_per_plant_max: 8,
      storage: 'Use fresh; refrigerate short term',
      image: '../../public/cucumber.webp',
      image2: '../../public/cucumber1.webp',
      image3: '../../public/cucumber2.webp',
    },
    {
      id: 20,
      name: 'Turnips',
      scientific_name: 'Brassica rapa subsp. rapa',
      description: 'Quick-growing root crop; greens edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Cool, dark, ventilated; 2–3 months',
      image: '../../public/turnip.webp',
      image2: '../../public/turnip1.webp',
      image3: '../../public/turnip2.webp',
    },
    {
      id: 21,
      name: 'Apples',
      scientific_name: 'Malus domestica',
      description:
        'Apple trees are hardy deciduous fruit trees that thrive in cool to temperate climates. They prefer full sun, well-drained fertile soil, and regular pruning to encourage strong growth and good fruiting.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 50,
      yield_per_plant_max: 200,
      storage:
        'Store apples in a cool, dark, well-ventilated place. Many varieties keep for months when refrigerated.',
      image: '../../public/apple.webp',
      image2: '../../public/apple1.webp',
      image3: '../../public/apple2.webp',
    },
    {
      id: 22,
      name: 'Avocado',
      scientific_name: 'Persea americana',
      description:
        'Avocado trees thrive in warm, frost-free regions with excellent drainage. They require full sun, protection from wind, and consistent moisture while young. Once established, they are hardy and productive evergreen fruit trees.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1825,
      yield_per_plant_min: 40,
      yield_per_plant_max: 150,
      storage:
        'Store avocados at room temperature until ripe. Once softened, refrigerate to extend shelf life for several days.',
      image: '../../public/avocado.webp',
      image2: '../../public/avocado1.webp',
      image3: '../../public/avocado2.webp',
    },
    {
      id: 23,
      name: 'Basil',
      scientific_name: 'Ocimum basilicum',
      description:
        'Basil is a tender annual herb that thrives in warm weather and rich, fertile soil. It requires full sun, consistent moisture, and regular harvesting to encourage bushy growth. Perfect for summer gardens in New Zealand.',
      soil_id: 4,
      spacing_id: 2,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage:
        'Store fresh basil stems in a glass of water at room temperature. Do not refrigerate as cold temperatures damage the leaves.',
      image: '../../public/basil.webp',
      image2: '../../public/basil1.webp',
      image3: '../../public/basil2.webp',
    },
    {
      id: 24,
      name: 'Blueberry',
      scientific_name: 'Vaccinium corymbosum',
      description:
        'Blueberries thrive in acidic, well-drained soil and full sun. They require consistent moisture and benefit from mulching with pine needles or bark to maintain acidity.',
      soil_id: 5,
      spacing_id: 6,
      requirements_id: 7,
      feeding_id: 6,
      staking_id: 1,
      days_to_harvest_min: 540,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 1,
      yield_per_plant_max: 4,
      storage:
        'Refrigerate berries for up to one week or freeze for long-term storage.',
      image: '../../public/blueberry.webp',
      image2: '../../public/blueberry1.webp',
      image3: '../../public/blueberry2.webp',
    },
    {
      id: 25,
      name: 'Chives',
      scientific_name: 'Allium schoenoprasum',
      description:
        'Chives are hardy perennial herbs that grow well in most NZ climates. They prefer full sun and rich soil with steady moisture.',
      soil_id: 4,
      spacing_id: 7,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage:
        'Refrigerate in an airtight bag or freeze chopped chives for later use.',
      image: '../../public/chives1.webp',
      image2: '../../public/chives.webp',
      image3: '../../public/chives2.webp',
    },
    {
      id: 26,
      name: 'Coriander',
      scientific_name: 'Coriandrum sativum',
      description:
        'Coriander prefers cooler weather and grows well in spring and autumn in New Zealand. It bolts quickly in summer heat.',
      soil_id: 4,
      spacing_id: 8,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 40,
      days_to_harvest_max: 55,
      yield_per_plant_min: 0.03,
      yield_per_plant_max: 0.1,
      storage:
        'Refrigerate stems in a jar of water; use promptly as leaves deteriorate quickly.',
      image: '../../public/coriander.webp',
      image2: '../../public/coriander1.webp',
      image3: '../../public/coriander2.webp',
    },
    {
      id: 27,
      name: 'Mint',
      scientific_name: 'Mentha spicata',
      description:
        'Mint is a vigorous, fast-spreading herb ideal for pots. It prefers rich, moist soil and part sun in NZ conditions.',
      soil_id: 4,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage:
        'Keep stems in water at room temperature or refrigerate loosely wrapped.',
      image: '../../public/mint.webp',
      image2: '../../public/mint1.webp',
      image3: '../../public/mint2.webp',
    },
    {
      id: 28,
      name: 'Parsley',
      scientific_name: 'Petroselinum crispum',
      description:
        'Parsley grows well year-round in many parts of NZ. It prefers rich soil and steady watering.',
      soil_id: 4,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.2,
      storage:
        'Refrigerate wrapped in a damp paper towel or stand stems in water.',
      image: '../../public/parsley.webp',
      image2: '../../public/parsley1.webp',
      image3: '../../public/parsley2.webp',
    },
    {
      id: 29,
      name: 'Sage',
      scientific_name: 'Salvia officinalis',
      description:
        'Sage thrives in warm, dry NZ summers and prefers full sun and well-drained soil.',
      soil_id: 2,
      spacing_id: 11,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 75,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.05,
      yield_per_plant_max: 0.15,
      storage: 'Air-dry or refrigerate wrapped loosely.',
      image: '../../public/sage.webp',
      image2: '../../public/sage1.webp',
      image3: '../../public/sage2.webp',
    },
    {
      id: 30,
      name: 'Strawberry',
      scientific_name: 'Fragaria × ananassa',
      description:
        'Strawberries thrive in sunny NZ gardens with rich, well-drained soil. Mulching helps suppress weeds and keep fruit clean.',
      soil_id: 4,
      spacing_id: 13,
      requirements_id: 5,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 1,
      storage: 'Refrigerate unwashed strawberries and use within a few days.',
      image: '../../public/strawberry.webp',
      image2: '../../public/strawberry1.webp',
      image3: '../../public/strawberry2.webp',
    },
    {
      id: 31,
      name: 'Watermelon',
      scientific_name: 'Citrullus lanatus',
      description:
        'Watermelons need hot summers, full sun, and well-drained soil. Best grown in warmer parts of New Zealand.',
      soil_id: 2,
      spacing_id: 14,
      requirements_id: 5,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 80,
      days_to_harvest_max: 100,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Store whole melons at room temperature; refrigerate once cut.',
      image: '../../public/watermelon.webp',
      image2: '../../public/watermelon1.webp',
      image3: '../../public/watermelon2.webp',
    },
    {
      id: 32,
      name: 'Feijoa',
      scientific_name: 'Acca sellowiana',
      description:
        'Feijoas are hardy NZ favourites that tolerate wind and cooler climates, producing fragrant fruit in autumn.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 10,
      yield_per_plant_max: 30,
      storage: 'Store feijoas in the fridge for up to a week or freeze pulp.',
      image: '../../public/feijoa.webp',
      image2: '../../public/feijoa1.webp',
      image3: '../../public/feijoa2.webp',
    },
    {
      id: 33,
      name: 'Garlic',
      scientific_name: 'Allium sativum',
      description:
        'Garlic grows well in NZ when planted in winter and harvested in mid-summer. It prefers free-draining soil and full sun.',
      soil_id: 2,
      spacing_id: 10,
      requirements_id: 2,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 210,
      days_to_harvest_max: 240,
      yield_per_plant_min: 0.04,
      yield_per_plant_max: 0.08,
      storage: 'Dry bulbs thoroughly and store in a cool, dark place.',
      image: '../../public/garlic.webp',
      image2: '../../public/garlic1.webp',
      image3: '../../public/garlic2.webp',
    },
    {
      id: 34,
      name: 'Lemon',
      scientific_name: 'Citrus limon',
      description:
        'Lemons thrive in warm NZ climates, especially the North Island. They need full sun, good drainage, and protection from frost.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage:
        'Store lemons at room temperature for 1 week or refrigerate for longer.',
      image: '../../public/lemon.webp',
      image2: '../../public/lemon1.webp',
      image3: '../../public/lemon2.webp',
    },
    {
      id: 35,
      name: 'Orange',
      scientific_name: 'Citrus sinensis',
      description:
        'Oranges grow best in frost-free NZ regions with plenty of sun. They require moist, fertile, well-drained soil.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 1095,
      days_to_harvest_max: 1460,
      yield_per_plant_min: 20,
      yield_per_plant_max: 80,
      storage: 'Store oranges in the fridge to extend freshness.',
      image: '../../public/orange.webp',
      image2: '../../public/orange1.webp',
      image3: '../../public/orange2.webp',
    },
    {
      id: 36,
      name: 'Peaches',
      scientific_name: 'Prunus persica',
      description:
        'Peaches grow well in many NZ regions, especially where summers are warm and dry. They require full sun and yearly pruning.',
      soil_id: 1,
      spacing_id: 6,
      requirements_id: 6,
      feeding_id: 10,
      staking_id: 4,
      days_to_harvest_min: 730,
      days_to_harvest_max: 1095,
      yield_per_plant_min: 20,
      yield_per_plant_max: 60,
      storage:
        'Store ripe peaches in the fridge for several days or freeze slices.',
      image: '../../public/peaches.webp',
      image2: '../../public/peaches1.webp',
      image3: '../../public/peaches2.webp',
    },
  ])
}
