export async function seed(knex) {
  // Deletes ALL existing entries
  await knex('vegetables').del()

  // Inserts seed entries
  await knex('vegetables').insert([
    {
      id: 1,
      name: 'Potatoes',
      scientific_name: 'Solanum tuberosum',
      description: 'Tuberous crop grown underground; staple in many gardens.',
      soil_id: 1,
      spacing_id: 1,
      requirements_id: 1,
      feeding_id: 1,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 120,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cool (10–15°C), dark, 2–4 months',
      image: '../../public/potato.webp',
      image2: '../../public/potatoes.webp',
      image3: '../../public/potatoes1.webp',
    },
    {
      id: 2,
      name: 'Onions',
      scientific_name: 'Allium cepa',
      description:
        'Bulb vegetable, grown from sets or seeds; good for long-term storage.',
      soil_id: 5,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.4,
      storage: 'Dry, ventilated, months',
      image: '../../public/onion.webp',
      image2: '../../public/onions.webp',
      image3: '../../public/onion1.webp',
    },
    {
      id: 3,
      name: 'Pumpkin / Squash',
      scientific_name: 'Cucurbita pepo',
      description:
        'Vining plant producing large, sweet fruit; great for storage.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 90,
      days_to_harvest_max: 130,
      yield_per_plant_min: 2,
      yield_per_plant_max: 5,
      storage: 'Cure 7–10 days, store 2–4 months',
      image: '../../public/pumpkin.webp',
      image2: '../../public/pumpkinplant.webp',
      image3: '../../public/pumpkinplant1.webp',
    },
    {
      id: 4,
      name: 'Broccoli',
      scientific_name: 'Brassica oleracea var. italica',
      description: 'Edible flowering heads rich in nutrition.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Refrigerate 1–2°C, up to a week',
      image: '../../public/broccoli.webp',
      image2: '../../public/broccoli3.webp',
      image3: '../../public/broccoli2.webp',
    },
    {
      id: 5,
      name: 'Cauliflower',
      scientific_name: 'Brassica oleracea var. botrytis',
      description: 'Compact white heads; needs consistent growth.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.4,
      yield_per_plant_max: 1.0,
      storage: 'Refrigerate 1–2°C, use within a week',
      image: '../../public/cauliflower.webp',
      image2: '../../public/cauliflower1.webp',
      image3: '../../public/cauliflower2.webp',
    },
    {
      id: 6,
      name: 'Cabbage',
      scientific_name: 'Brassica oleracea var. capitata',
      description: 'Dense leafy head vegetable.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 120,
      yield_per_plant_min: 0.5,
      yield_per_plant_max: 1.5,
      storage: 'Cool 0–2°C, several weeks',
      image: '../../public/cabbage.webp',
      image2: '../../public/cabbage3.webp',
      image3: '../../public/cabbage1.webp',
    },
    {
      id: 7,
      name: 'Lettuce',
      scientific_name: 'Lactuca sativa',
      description: 'Leafy salad green, prefers cool moist conditions.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 45,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.3,
      storage: 'Refrigerate 0–2°C, 5–7 days',
      image: '../../public/lettuce.webp',
      image2: '../../public/lettuce1.webp',
      image3: '../../public/lettuce2.webp',
    },
    {
      id: 8,
      name: 'Spinach',
      scientific_name: 'Spinacia oleracea',
      description: 'Leafy green, fast-growing in cool seasons.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 30,
      days_to_harvest_max: 50,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Refrigerate 0–2°C, use within days',
      image: '../../public/spinach.webp',
      image2: '../../public/spinach1.webp',
      image3: '../../public/spinach2.webp',
    },
    {
      id: 9,
      name: 'Silverbeet / Swiss Chard',
      scientific_name: 'Beta vulgaris subsp. cicla',
      description: 'Productive leafy green with colourful stems.',
      soil_id: 5,
      spacing_id: 5,
      requirements_id: 5,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate 0–2°C, ~5–7 days',
      image: '../../public/silverbeet.webp',
      image2: '../../public/silverbeet1.webp',
      image3: '../../public/silverbeet3.webp',
    },
    {
      id: 10,
      name: 'Kale',
      scientific_name: 'Brassica oleracea var. sabellica',
      description: 'Hardy leafy green; tolerates frost.',
      soil_id: 4,
      spacing_id: 4,
      requirements_id: 4,
      feeding_id: 4,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate, use within 7–10 days',
      image: '../../public/kale.webp',
      image2: '../../public/kale1.webp',
      image3: '../../public/kale3.webp',
    },
    {
      id: 11,
      name: 'Peas (Garden / Snap)',
      scientific_name: 'Pisum sativum',
      description: 'Sweet pods, climbing or bush varieties.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 60,
      days_to_harvest_max: 75,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.6,
      storage: 'Refrigerate 0–2°C, 3–5 days',
      image: '../../public/sweet-pea.webp',
      image2: '../../public/peas1.webp',
      image3: '../../public/peas2.webp',
    },
    {
      id: 12,
      name: 'Beans (Green / Broad)',
      scientific_name: 'Phaseolus vulgaris',
      description: 'Climbing or bush legumes with edible pods.',
      soil_id: 2,
      spacing_id: 2,
      requirements_id: 2,
      feeding_id: 2,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.5,
      storage: 'Refrigerate 0–2°C, 3–5 days',
      image: '../../public/green-beans.webp',
      image2: '../../public/greenbean1.webp',
      image3: '../../public/greenbean2.webp',
    },
    {
      id: 13,
      name: 'Carrots',
      scientific_name: 'Daucus carota',
      description: 'Root vegetable, prefers deep loose soil.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 0.1,
      yield_per_plant_max: 0.2,
      storage: 'Cool, dark, ventilated, 2–3 months',
      image: '../../public/carrots.webp',
      image2: '../../public/carrots3.webp',
      image3: '../../public/carrots4.webp',
    },
    {
      id: 14,
      name: 'Beetroot',
      scientific_name: 'Beta vulgaris',
      description: 'Root vegetable; leaves edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 60,
      days_to_harvest_max: 90,
      yield_per_plant_min: 0.2,
      yield_per_plant_max: 0.4,
      storage: 'Cool dark, 2–3 months',
      image: '../../public/beetroot.webp',
      image2: '../../public/beetroot1.webp',
      image3: '../../public/beetroot3.webp',
    },
    {
      id: 15,
      name: 'Parsnips',
      scientific_name: 'Pastinaca sativa',
      description: 'Sweet root crop; flavor improves after frost.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 120,
      days_to_harvest_max: 150,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.5,
      storage: 'Cool, dark, ventilated; 3–4 months',
      image: '../../public/parsnip-plant.webp',
      image2: '../../public/parsnip1.webp',
      image3: '../../public/parsnip2.webp',
    },
    {
      id: 16,
      name: 'Kumara',
      scientific_name: 'Ipomoea batatas',
      description: 'Sweet potato; needs warm soil and curing before storage.',
      soil_id: 3,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 1,
      days_to_harvest_min: 100,
      days_to_harvest_max: 140,
      yield_per_plant_min: 1,
      yield_per_plant_max: 3,
      storage: 'Cure 7–10 days, store at 12–15°C',
      image: '../../public/kumera.webp',
      image2: '../../public/kumera1.webp',
      image3: '../../public/kumera2.webp',
    },
    {
      id: 17,
      name: 'Tomatoes',
      scientific_name: 'Solanum lycopersicum',
      description: 'Warm-season fruiting plant; needs support.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 3,
      yield_per_plant_max: 6,
      storage: 'Best fresh; short refrigeration possible',
      image: '../../public/tomato.webp',
      image2: '../../public/tomatoes1.webp',
      image3: '../../public/tomatoplant2.webp',
    },
    {
      id: 18,
      name: 'Capsicum / Bell Peppers',
      scientific_name: 'Capsicum annuum',
      description: 'Warm-season fruiting vegetable, sweet or hot varieties.',
      soil_id: 1,
      spacing_id: 4,
      requirements_id: 1,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 70,
      days_to_harvest_max: 100,
      yield_per_plant_min: 2,
      yield_per_plant_max: 4,
      storage: 'Cool, ~7–10°C, 1–2 weeks',
      image: '../../public/bell-pepper.webp',
      image2: '../../public/bellpepper.webp',
      image3: '../../public/bellpepper1.webp',
    },
    {
      id: 19,
      name: 'Cucumbers',
      scientific_name: 'Cucumis sativus',
      description: 'Vining summer crop, best supported on trellis.',
      soil_id: 1,
      spacing_id: 3,
      requirements_id: 3,
      feeding_id: 3,
      staking_id: 2,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 3,
      yield_per_plant_max: 8,
      storage: 'Use fresh; refrigerate short term',
      image: '../../public/cucumber.webp',
      image2: '../../public/cucumber1.webp',
      image3: '../../public/cucumber2.webp',
    },
    {
      id: 20,
      name: 'Turnips',
      scientific_name: 'Brassica rapa subsp. rapa',
      description: 'Quick-growing root crop; greens edible.',
      soil_id: 3,
      spacing_id: 5,
      requirements_id: 3,
      feeding_id: 5,
      staking_id: 1,
      days_to_harvest_min: 50,
      days_to_harvest_max: 70,
      yield_per_plant_min: 0.3,
      yield_per_plant_max: 0.8,
      storage: 'Cool, dark, ventilated; 2–3 months',
      image: '../../public/turnip.webp',
      image2: '../../public/turnip1.webp',
      image3: '../../public/turnip2.webp',
    },
  ])
}
